/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_if_1;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner miScan = new Scanner(System.in);
        
        System.out.println("Introduzca la hora: ");
        int hora = miScan.nextInt();
        
        if(hora >= 6 && hora < 12){
            
            System.out.println("¡Buenos días!");
        }else if (hora >= 13 && hora < 20){
            
            System.out.println("¡Buenas tardes!");
        }else{
            
            System.out.println("¡Buenas noches!");
        }
    }
}
